services:
  byom-edge:
    image: tdchub/ocei:latest
    container_name: byom-edge
    restart: unless-stopped
    ports:
      - "1880:1880"
    volumes:
      - ocei-keys:/data/keys
      - ocei-queue:/data/pending
      - ocei-queue:/data/queue

volumes:
  ocei-keys:
  ocei-queue: